### ISSUE TITLE
Unterstützung für Dark Mode 

### ISSUE THREAD

**Issue by makigumo** [makigumo/wadoku-mac-dic#6]
Benötigt u. a. explizite Angabe von `DCSDictionaryUseSystemAppearance` in der `Info.plist`.

CSS-Angaben:
```css
html {
  -apple-color-filter: apple-invert-lightness();
}
body {
  font: -apple-system-body;
  font-family: -apple-system;
}
/* @media (prefers-dark-interface) { */
@media (prefers-color-scheme: dark) {
  img {
    filter: invert(100%);
    text-decoration: none;
  }
}
a {
  color: -webkit-link;
}
```
Farbwerte:
* `-apple-system-label`
* `-apple-system-secondary-label`
* `-apple-system-tertiary-label`
* `-apple-system-text-background`
